name: build and push docker-image

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: mateusmedeirosgarcia/frontend-tcc:latest
      - 
        name: Webhook Action
        uses: joelwmale/webhook-action@2.3.2
        with:
          url: ${{ secrets.WEBHOOK }}
